//
//  FoundationModelsSupport.swift
//  MLAI
//
//  Apple Foundation Models (macOS 26+) integration for chat inference.
//

import Foundation

#if canImport(FoundationModels)
import FoundationModels
#endif

enum FoundationModelsSupport {

    enum AvailabilityStatus: Equatable {
        case available
        case unavailable(String)
    }

    static var availabilityStatus: AvailabilityStatus {
        #if canImport(FoundationModels)
        if #available(macOS 26.0, *) {
            let model = SystemLanguageModel.default
            switch model.availability {
                case .available:
                    return .available
                case .unavailable(let reason):
                    return .unavailable(String(describing: reason))
            }
        }
        #endif
        return .unavailable("Requires macOS 26 with Apple Intelligence enabled.")
    }

    static var isAvailable: Bool {
        if case .available = availabilityStatus {
            return true
        }
        return false
    }

    static var availabilityDescription: String {
        switch availabilityStatus {
            case .available:
                return "Available"
            case .unavailable(let reason):
                return "Unavailable: \(reason)"
        }
    }

}

/// Errors from the Foundation Models client.
enum FoundationModelsError: LocalizedError {
    case sessionUnavailable
    case emptyResponse
    case contextExhausted
    case streamingFailed(String)

    var errorDescription: String? {
        switch self {
            case .sessionUnavailable:
                return "Foundation Models session is not available."
            case .emptyResponse:
                return "Foundation Models returned an empty response."
            case .contextExhausted:
                return "Foundation Models context window has been exhausted."
            case .streamingFailed(let reason):
                return "Foundation Models streaming failed: \(reason)"
        }
    }
}

#if canImport(FoundationModels)
/// A structured response that can be generated by Foundation Models using guided generation.
@available(macOS 26.0, *)
@Generable
struct StructuredResponse {
    @Guide(description: "A concise summary of the response")
    var summary: String
    @Guide(description: "Key points extracted from the response")
    var keyPoints: [String]
    @Guide(description: "Confidence level from 0.0 to 1.0")
    var confidence: Double
}

@available(macOS 26.0, *)
@MainActor
final class FoundationModelsClient {

    static let shared = FoundationModelsClient()

    private var session: LanguageModelSession
    private var lastSystemPrompt: String

    /// Tracks conversation turn count for context window management.
    private(set) var turnCount: Int = 0
    private let maxTurns: Int = 20

    init(systemPrompt: String = InferenceSettings.systemPrompt) {
        self.lastSystemPrompt = systemPrompt
        self.session = LanguageModelSession(instructions: systemPrompt)
    }

    func updateSystemPrompt(_ systemPrompt: String) {
        guard systemPrompt != lastSystemPrompt else { return }
        resetSession(systemPrompt: systemPrompt)
    }

    func resetSession(systemPrompt: String) {
        self.lastSystemPrompt = systemPrompt
        self.session = LanguageModelSession(instructions: systemPrompt)
        self.turnCount = 0
    }

    /// Sends a prompt and returns the model's text response.
    func respond(to prompt: String) async throws -> String {
        let response = try await session.respond(to: prompt)
        let trimmed = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            throw FoundationModelsError.emptyResponse
        }
        return response.content
    }

    // MARK: - Streaming Response

    /// Streams a response token by token, calling `onPartial` with each new delta.
    func respondStreaming(
        to prompt: String,
        onPartial: @Sendable (String) -> Void
    ) async throws -> String {
        let stream = session.streamResponse(to: prompt)
        var fullText = ""
        for try await partial in stream {
            let newContent = partial.content
            if newContent.count > fullText.count {
                let delta = String(newContent.dropFirst(fullText.count))
                onPartial(delta)
            }
            fullText = newContent
        }
        let trimmed = fullText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            throw FoundationModelsError.emptyResponse
        }
        return fullText
    }

    // MARK: - Guided Generation

    /// Generates a structured response using the `@Generable` macro.
    func respondStructured(to prompt: String) async throws -> StructuredResponse {
        let response = try await session.respond(to: prompt, generating: StructuredResponse.self)
        return response.content
    }

    // MARK: - Session Management

    /// Responds and tracks turns, auto-resetting when the context window is exhausted.
    func respondWithSessionManagement(
        to prompt: String,
        systemPrompt: String = InferenceSettings.systemPrompt
    ) async throws -> String {
        turnCount += 1
        if turnCount > maxTurns {
            resetSession(systemPrompt: systemPrompt)
            turnCount = 1
        }
        do {
            let response = try await session.respond(to: prompt)
            return response.content
        } catch {
            // If context is exhausted, reset and retry once
            resetSession(systemPrompt: systemPrompt)
            turnCount = 1
            let response = try await session.respond(to: prompt)
            return response.content
        }
    }

}
#endif
